FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY apps/web/package*.json ./
RUN npm install

# Copy source code
COPY apps/web ./

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
