# A generic, single database configuration.

[alembic]
# path to migration versions
script_location = alembic
# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s
# sys.path for loading application models
prepend_sys_path = .

# database URL — overridden by env.py at runtime
sqlalchemy.url = postgresql+asyncpg://enlight_sales_os_user:enlight_sales_os_password@localhost:5432/enlight_sales_os_db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
